In [7]:
import numpy as np
import matplotlib.pyplot as plt 

In [8]:
x_data = np.array([[1,2],[2,3],[3,1],[4,4],[2,4]])
y_data = np.array([8,13,9,20,16])
print(x_data)
print(x_data[0],'\n')
x_data=x_data.transpose()
print(x_data)
print(x_data.shape,y_data.shape)
print(x_data[0])

[[1 2]
 [2 3]
 [3 1]
 [4 4]
 [2 4]]
[1 2] 

[[1 2 3 4 2]
 [2 3 1 4 4]]
(2, 5) (5,)
[1 2 3 4 2]


In [9]:
w1=np.random.randint(0,9)
w2=np.random.randint(0,9)
b=np.random.randint(0,9)
print(w1,w2,b)

7 2 5


In [10]:
learning_rate=0.01

In [11]:
def cost_function(x,y,w1,w2,b):
    m=len(x)
    predicted=w1*x[0]+w2*x[1]+b
    error=predicted-y
    cost = (1 / (2 * m)) * np.sum(error**2)
    return cost

In [12]:
cost_function(x_data,y_data,w1,w2,b)

282.75

In [13]:
m = len(x_data)
epochs=5000
for iteration in range(epochs):
    predictions = w1*x_data[0]+w2*x_data[1]+b
    error = predictions - y_data
    df_b = (1 / m) * np.sum(error)
    df_w1 = (1 / m) * np.sum(error * x_data[0])
    df_w2 = (1 / m) * np.sum(error * x_data[1])
    b -= learning_rate * df_b
    w1 -= learning_rate * df_w1
    w2 -= learning_rate * df_w2
cost = cost_function(x_data, y_data, w1,w2, b)
print(f"Iteration {iteration}, Cost: {cost}")
print(w1,w2,b)

Iteration 4999, Cost: 1.5833431823625884e-10
1.999993303625573 2.9999941258034504 3.584709586680273e-05
