In [1]:
import tensorflow as tf

In [2]:
print(tf.config.list_physical_devices('CPU'))

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [3]:
x =tf.constant(2)
print(x)
x= tf.constant(4,shape=(2,4))
print(x)
x=tf.ones((2,2))
print(x)
x= tf.random.normal((3,2),mean=3,stddev=2)
print(x,'\n')
x=tf.range(0,100,2)
print(x)
x=tf.reshape(x,(10,5))
print(x,'\n')
x=tf.transpose(x)
print(x)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[4 4 4 4]
 [4 4 4 4]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.9307468 5.5276127]
 [4.137413  4.0472484]
 [2.9228036 1.5374001]], shape=(3, 2), dtype=float32) 

tf.Tensor(
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98], shape=(50,), dtype=int32)
tf.Tensor(
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]], shape=(10, 5), dtype=int32) 

tf.Tensor(
[[ 0 10 20 30 40 50 60 70 80 90]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 8 18 28 38 48 58 68 78 88 98]], shape=(5, 10), dtype=int32)
